# Generated by Django 5.2.15 on 2026-06-12 06:58

import apps.advances.models
import apps.core.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('minimum_service_days', models.PositiveIntegerField(default=30)),
                ('max_earned_wage_percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_requests_per_cycle', models.PositiveSmallIntegerField(default=1)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approver_roles', models.JSONField(default=apps.advances.models.default_advance_approver_roles)),
                ('acknowledgement_text', models.TextField(default='I understand this amount will be deducted from my payroll.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company')),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_limit_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acknowledgement', models.BooleanField(default=False)),
                ('acknowledgement_text', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('deducted', 'Deducted'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('requested_via', models.CharField(default='admin', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_reference', apps.core.fields.EncryptedTextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company')),
            ],
        ),
    ]
