# Generated by Django 5.2.15 on 2026-06-12 06:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advances', '0002_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_requests', to='workforce.worker'),
        ),
        migrations.AddConstraint(
            model_name='advancepolicy',
            constraint=models.UniqueConstraint(fields=('company',), name='one_advance_policy_per_company'),
        ),
        migrations.AddIndex(
            model_name='advancerequest',
            index=models.Index(fields=['company', 'worker', 'status'], name='advances_ad_company_def404_idx'),
        ),
        migrations.AddConstraint(
            model_name='advancerequest',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__gt', Decimal('0'))), name='advance_requested_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='advancerequest',
            constraint=models.CheckConstraint(condition=models.Q(('approved_amount__gte', Decimal('0'))), name='advance_approved_amount_nonnegative'),
        ),
    ]
