# Generated by Django 5.2.15 on 2026-06-12 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_minutes', models.PositiveIntegerField()),
                ('approved_minutes', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=40)),
                ('occurred_at', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exception_type', models.CharField(choices=[('late', 'Late arrival'), ('early_leave', 'Early departure'), ('missing_checkout', 'Missing checkout'), ('geo_mismatch', 'Outside geofence'), ('duplicate', 'Duplicate capture'), ('manual_override', 'Manual override'), ('photo_missing', 'Required photo missing'), ('sync_delay', 'Delayed offline sync'), ('tamper', 'Potential tampering')], max_length=30)),
                ('reason', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(db_index=True)),
                ('check_in_at', models.DateTimeField()),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('verification_method', models.CharField(choices=[('qr', 'QR code'), ('id', 'Worker ID'), ('photo', 'Photo'), ('face', 'Face verification'), ('bulk', 'Bulk supervisor mark'), ('manual', 'Manual exception'), ('kiosk', 'Kiosk')], max_length=20)),
                ('source', models.CharField(choices=[('online', 'Online'), ('offline_sync', 'Offline sync'), ('kiosk', 'Kiosk'), ('import', 'Import')], default='online', max_length=20)),
                ('device_id', models.CharField(max_length=255)),
                ('original_captured_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Checked in'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Payroll locked')], default='open', max_length=20)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='attendance/%Y/%m/%d/')),
                ('idempotency_key', models.CharField(max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company')),
            ],
        ),
    ]
