# Generated by Django 5.2.15 on 2026-06-12 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('organizations', '0001_initial'),
        ('sites', '0001_initial'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='roster_assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='sites.rosterassignment'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='sites.shifttemplate'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='sites.site'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='workforce.worker'),
        ),
        migrations.AddField(
            model_name='attendanceexception',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_requests', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_overtime', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_overtime', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['company', 'site', 'work_date', 'status'], name='attendance__company_0dcb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['company', 'worker', 'work_date'], name='attendance__company_837d19_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_attendance_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_at__isnull', True), ('check_out_at__gte', models.F('check_in_at')), _connector='OR'), name='attendance_checkout_after_checkin'),
        ),
        migrations.AddIndex(
            model_name='attendanceexception',
            index=models.Index(fields=['company', 'status', 'exception_type'], name='attendance__company_efa357_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['company', 'created_at'], name='attendance__company_6df03e_idx'),
        ),
    ]
