# Generated by Django 5.2.15 on 2026-06-12 08:17

from django.conf import settings
from django.db import migrations, models


def migrate_time_only_attendance(apps, schema_editor):
    AttendanceException = apps.get_model("attendance", "AttendanceException")
    AttendanceRecord = apps.get_model("attendance", "AttendanceRecord")

    AttendanceException.objects.exclude(
        exception_type__in=["late", "early_leave"]
    ).delete()
    AttendanceException.objects.filter(status__in=["approved", "resolved"]).update(
        status="resolved",
        decision="full_day",
    )
    AttendanceException.objects.filter(status="rejected").update(decision="rejected")

    for record in AttendanceRecord.objects.all().iterator():
        record.check_in_latitude = None
        record.check_in_longitude = None
        record.check_out_latitude = None
        record.check_out_longitude = None
        record.flags = [
            flag for flag in record.flags if flag in {"late", "early_leave"}
        ]
        decisions = set(
            record.exceptions.exclude(decision="").values_list("decision", flat=True)
        )
        has_open_exception = record.exceptions.filter(status="open").exists()
        if "rejected" in decisions:
            record.outcome = "rejected"
            record.payable_fraction = 0
            record.status = "rejected"
        elif record.status == "pending" and not has_open_exception:
            record.status = "approved" if record.check_out_at else "open"
        record.save(
            update_fields=[
                "check_in_latitude",
                "check_in_longitude",
                "check_out_latitude",
                "check_out_longitude",
                "flags",
                "status",
                "outcome",
                "payable_fraction",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('organizations', '0001_initial'),
        ('sites', '0002_initial'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceexception',
            name='decision',
            field=models.CharField(blank=True, choices=[('full_day', 'Accept full attendance'), ('half_day', 'Mark half day'), ('rejected', 'Reject attendance')], max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='outcome',
            field=models.CharField(choices=[('full_day', 'Full day'), ('half_day', 'Half day'), ('rejected', 'Rejected')], default='full_day', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='payable_fraction',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="attendanceexception",
            name="exception_type",
            field=models.CharField(
                choices=[
                    ("late", "Late arrival"),
                    ("early_leave", "Early departure"),
                ],
                max_length=30,
            ),
        ),
        migrations.RunPython(migrate_time_only_attendance, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('payable_fraction__gte', 0), ('payable_fraction__lte', 1)), name='attendance_payable_fraction_valid'),
        ),
    ]
