# Generated by Django 5.2.15 on 2026-06-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendanceexception_decision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='check_in_latitude',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='check_in_longitude',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='check_out_latitude',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='check_out_longitude',
        ),
    ]
