# Generated by Django 5.2.15 on 2026-06-12 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('sites', '0001_initial'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterassignment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_assignments', to='workforce.worker'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_assignments', to='sites.shifttemplate'),
        ),
        migrations.AddField(
            model_name='site',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_assignments', to='sites.site'),
        ),
        migrations.AddField(
            model_name='sitesupervisor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='sitesupervisor',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_links', to='sites.site'),
        ),
        migrations.AddField(
            model_name='sitesupervisor',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workertransfer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='workertransfer',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workertransfer',
            name='from_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='sites.rosterassignment'),
        ),
        migrations.AddField(
            model_name='workertransfer',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workertransfer',
            name='to_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.shifttemplate'),
        ),
        migrations.AddField(
            model_name='workertransfer',
            name='to_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
        migrations.AddField(
            model_name='workertransfer',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workforce.worker'),
        ),
        migrations.AddConstraint(
            model_name='shifttemplate',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_shift_template'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_site'),
        ),
        migrations.AddIndex(
            model_name='rosterassignment',
            index=models.Index(fields=['company', 'site', 'date', 'status'], name='sites_roste_company_b8074f_idx'),
        ),
        migrations.AddConstraint(
            model_name='rosterassignment',
            constraint=models.UniqueConstraint(fields=('worker', 'date'), name='one_roster_assignment_per_worker_day'),
        ),
        migrations.AddConstraint(
            model_name='sitesupervisor',
            constraint=models.UniqueConstraint(fields=('site', 'supervisor'), name='unique_site_supervisor'),
        ),
        migrations.AddIndex(
            model_name='workertransfer',
            index=models.Index(fields=['company', 'created_at'], name='sites_worke_company_d1cffb_idx'),
        ),
    ]
