# Generated by Django 5.2.15 on 2026-06-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='geofence_radius_meters',
        ),
        migrations.RemoveField(
            model_name='site',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='site',
            name='longitude',
        ),
    ]
