# Generated by Django 5.2.15 on 2026-06-12 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('organizations', '0001_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationoutbox',
            name='recipient_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workforce.worker'),
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='notifications.notificationoutbox'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='workerotpchallenge',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='workerotpchallenge',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.worker'),
        ),
        migrations.AddField(
            model_name='workerportalsession',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='workerportalsession',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to='workforce.worker'),
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_a9ca0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationoutbox',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key', 'channel'), name='unique_notification_idempotency'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['company', 'created_at'], name='notificatio_company_f60a15_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('company', 'key', 'channel', 'language'), name='unique_notification_template'),
        ),
        migrations.AddIndex(
            model_name='workerotpchallenge',
            index=models.Index(fields=['worker', 'expires_at', 'consumed_at'], name='notificatio_worker__f174a1_idx'),
        ),
        migrations.AddIndex(
            model_name='workerportalsession',
            index=models.Index(fields=['company', 'created_at'], name='notificatio_company_6a1fc1_idx'),
        ),
    ]
