# Generated by Django 5.2.15 on 2026-06-12 06:58

import apps.disputes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_worker_visible', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(default='file', max_length=20)),
                ('file', models.FileField(blank=True, upload_to=apps.disputes.models.dispute_evidence_path)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispute_type', models.CharField(choices=[('absent_but_present', 'Absent but present'), ('overtime_missing', 'Overtime missing'), ('wrong_deduction', 'Wrong deduction'), ('salary_not_received', 'Salary not received'), ('advance_issue', 'Advance issue'), ('wrong_site', 'Wrong site'), ('other', 'Other')], max_length=40)),
                ('date_reference', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('supervisor_review', 'Supervisor review'), ('hr_review', 'HR review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('raised_via', models.CharField(default='admin', max_length=20)),
                ('sla_due_at', models.DateTimeField()),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company')),
            ],
        ),
    ]
