# Generated by Django 5.2.15 on 2026-06-12 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disputes', '0002_initial'),
        ('organizations', '0001_initial'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='workforce.worker'),
        ),
        migrations.AddField(
            model_name='disputecomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputecomment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='disputecomment',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='disputes.dispute'),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='dispute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='disputes.dispute'),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['company', 'status', 'sla_due_at'], name='disputes_di_company_e02e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['company', 'worker', 'date_reference'], name='disputes_di_company_c334c1_idx'),
        ),
        migrations.AddIndex(
            model_name='disputecomment',
            index=models.Index(fields=['company', 'created_at'], name='disputes_di_company_ba6b45_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeevidence',
            index=models.Index(fields=['company', 'created_at'], name='disputes_di_company_f27629_idx'),
        ),
    ]
