# Generated by Django 5.2.15 on 2026-06-12 06:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('payroll', '0001_initial'),
        ('sites', '0001_initial'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywageledger',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wage_ledgers', to='workforce.worker'),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workforce.worker'),
        ),
        migrations.AddField(
            model_name='payrollcycle',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollcycle',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='payrollcycle',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_payroll_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollcycle',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payroll_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='applied_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_adjustments', to='payroll.payrollcycle'),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='payroll.payrollcycle'),
        ),
        migrations.AddField(
            model_name='payrollexport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='payrollexport',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='payroll.payrollcycle'),
        ),
        migrations.AddField(
            model_name='payrollexport',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='payroll.payrollcycle'),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='workforce.worker'),
        ),
        migrations.AddField(
            model_name='wagerule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company'),
        ),
        migrations.AddField(
            model_name='wagerule',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddField(
            model_name='wagerule',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workforce.worker'),
        ),
        migrations.AddIndex(
            model_name='dailywageledger',
            index=models.Index(fields=['company', 'work_date', 'status'], name='payroll_dai_company_b8cb33_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailywageledger',
            constraint=models.UniqueConstraint(fields=('worker', 'work_date'), name='unique_daily_worker_wage_ledger'),
        ),
        migrations.AddConstraint(
            model_name='dailywageledger',
            constraint=models.CheckConstraint(condition=models.Q(('net_estimate__gte', 0)), name='daily_wage_net_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='payrollcycle',
            constraint=models.UniqueConstraint(fields=('company', 'period_start', 'period_end', 'version'), name='unique_payroll_cycle_version'),
        ),
        migrations.AddConstraint(
            model_name='payrollcycle',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='payroll_period_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['company', 'created_at'], name='payroll_pay_company_f681db_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollexport',
            constraint=models.UniqueConstraint(fields=('cycle', 'export_type', 'version'), name='unique_payroll_export_version'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('cycle', 'worker'), name='unique_cycle_worker_line'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.CheckConstraint(condition=models.Q(('net_pay__gte', Decimal('0'))), name='payroll_line_net_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='wagerule',
            index=models.Index(fields=['company', 'is_active', 'effective_from'], name='payroll_wag_company_89474b_idx'),
        ),
    ]
