# Generated by Django 5.2.15 on 2026-06-12 09:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def copy_existing_net_pay(apps, schema_editor):
    PayrollLine = apps.get_model("payroll", "PayrollLine")
    for line in PayrollLine.objects.only("id", "net_pay").iterator():
        PayrollLine.objects.filter(pk=line.pk).update(calculated_net_pay=line.net_pay)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_companypolicy_half_day_deduction_percentage'),
        ('payroll', '0002_initial'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollline',
            name='calculated_net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(copy_existing_net_pay, migrations.RunPython.noop),
        migrations.AddField(
            model_name='payrollline',
            name='manual_net_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='manual_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='manual_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_line_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='manual_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.CheckConstraint(condition=models.Q(('manual_net_pay__isnull', True), ('manual_net_pay__gte', Decimal('0')), _connector='OR'), name='payroll_line_manual_net_nonnegative'),
        ),
    ]
