# Generated by Django 5.2.15 on 2026-06-12 06:58

import apps.core.fields
import apps.workforce.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_code', models.CharField(max_length=40)),
                ('full_name', models.CharField(max_length=180)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('notification_channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('both', 'Both'), ('none', 'None')], default='whatsapp', max_length=12)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('employment_start_date', models.DateField()),
                ('employment_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('wage_type', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('hourly', 'Hourly'), ('shift', 'Per shift')], max_length=20)),
                ('basic_wage', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('allowances', models.JSONField(blank=True, default=list)),
                ('payroll_method', models.CharField(blank=True, max_length=40)),
                ('bank_routing_code', apps.core.fields.EncryptedTextField(blank=True)),
                ('bank_account_or_card', apps.core.fields.EncryptedTextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company')),
                ('default_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_workers', to='sites.site')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_workers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['worker_code'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(choices=[('privacy', 'Privacy notice'), ('photo', 'Photo attendance'), ('biometric', 'Biometric processing'), ('location', 'Location processing'), ('notifications', 'Worker notifications')], max_length=30)),
                ('version', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=10)),
                ('channel', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('withdrawn', 'Withdrawn'), ('declined', 'Declined')], max_length=20)),
                ('captured_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='workforce.worker')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('emirates_id', 'Emirates ID'), ('passport', 'Passport'), ('work_permit', 'Work permit'), ('contract', 'Employment contract'), ('other', 'Other')], max_length=30)),
                ('reference_number', apps.core.fields.EncryptedTextField(blank=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('file', models.FileField(blank=True, upload_to=apps.workforce.models.worker_document_path)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workforce.worker')),
            ],
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['company', 'status'], name='workforce_w_company_89ae60_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['company', 'phone'], name='workforce_w_company_91cf80_idx'),
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(fields=('company', 'worker_code'), name='unique_company_worker_code'),
        ),
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.CheckConstraint(condition=models.Q(('basic_wage__gte', 0)), name='worker_basic_wage_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['worker', 'consent_type', 'captured_at'], name='workforce_c_worker__7ef474_idx'),
        ),
        migrations.AddConstraint(
            model_name='workerdocument',
            constraint=models.UniqueConstraint(fields=('worker', 'document_type', 'reference_number'), name='unique_worker_document'),
        ),
    ]
