# Generated by Django 5.2.15 on 2026-06-12 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='employment_category',
            field=models.CharField(choices=[('site_worker', 'Site worker'), ('staff', 'Staff employee')], default='site_worker', max_length=20),
        ),
        migrations.AddField(
            model_name='worker',
            name='user_account',
            field=models.OneToOneField(blank=True, help_text="Optional login account linked to this employee's payroll identity.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
