# Generated by Django 5.2.15 on 2026-06-12 06:58

import apps.core.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_license_number', apps.core.fields.EncryptedTextField(blank=True)),
                ('mohre_establishment_number', apps.core.fields.EncryptedTextField(blank=True)),
                ('emirate', models.CharField(blank=True, max_length=30)),
                ('industry', models.CharField(blank=True, max_length=80)),
                ('timezone', models.CharField(default='Asia/Dubai', max_length=50)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('payroll_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('four_weekly', 'Every four weeks')], default='monthly', max_length=20)),
                ('payroll_cutoff_day', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normal_daily_hours', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('normal_weekly_hours', models.DecimalField(decimal_places=2, default=48, max_digits=5)),
                ('max_consecutive_hours', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('minimum_break_minutes', models.PositiveSmallIntegerField(default=60)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.25, max_digits=4)),
                ('night_overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('night_period_start', models.TimeField(default='22:00')),
                ('night_period_end', models.TimeField(default='04:00')),
                ('weekly_rest_days', models.PositiveSmallIntegerField(default=1)),
                ('ramadan_enabled', models.BooleanField(default=True)),
                ('ramadan_daily_reduction_hours', models.DecimalField(decimal_places=2, default=2, max_digits=4)),
                ('ramadan_start', models.DateField(blank=True, null=True)),
                ('ramadan_end', models.DateField(blank=True, null=True)),
                ('midday_break_enabled', models.BooleanField(default=True)),
                ('midday_break_start_date', models.CharField(default='06-15', max_length=5)),
                ('midday_break_end_date', models.CharField(default='09-15', max_length=5)),
                ('midday_break_start_time', models.TimeField(default='12:30')),
                ('midday_break_end_time', models.TimeField(default='15:00')),
                ('require_attendance_photo', models.BooleanField(default=False)),
                ('require_biometric_consent', models.BooleanField(default=True)),
                ('allow_manual_attendance', models.BooleanField(default=True)),
                ('attendance_edit_window_hours', models.PositiveSmallIntegerField(default=48)),
                ('data_retention', models.JSONField(blank=True, default=dict, help_text='Retention periods in days by data category.')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='policy', to='organizations.company')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['company', 'created_at'], name='organizatio_company_7b7ce3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('enabled', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'key'), name='unique_company_feature')],
            },
        ),
        migrations.CreateModel(
            name='WPSConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_name', models.CharField(blank=True, max_length=150)),
                ('employer_bank_routing_code', apps.core.fields.EncryptedTextField(blank=True)),
                ('employer_account', apps.core.fields.EncryptedTextField(blank=True)),
                ('employer_reference', apps.core.fields.EncryptedTextField(blank=True)),
                ('file_format', models.CharField(default='generic_sif', max_length=40)),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wps_configuration', to='organizations.company')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['company', 'created_at'], name='organizatio_company_11c82b_idx')],
            },
        ),
    ]
