# Generated by Django 5.2.15 on 2026-06-12 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicy',
            name='half_day_deduction_percentage',
            field=models.DecimalField(decimal_places=2, default=50, help_text="Percentage of a normal day's pay deducted for a half-day decision.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
